name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Build frontend
      working-directory: frontend
      run: |
        npm install
        npm run build
        
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        # Deploy frontend
        npx vercel --token $VERCEL_TOKEN --prod frontend
        
        # Deploy backend
        cd $GITHUB_WORKSPACE
        node server.js &
